### ISSUE TITLE
Add unit test of user permissions merged with group permissions

### ISSUE THREAD

**Issue by yjacques940** [CAUCA-9-1-1/cause-security-management#16]

**Comment by iamkinetic** [comment]
Est-ce que ces tests unitaires ont été fait?

**Comment by iamkinetic** [comment]
@yjacques940 Ont-ils été fait?

**Comment by iamkinetic** [comment]
Faut-il garder ce point ouvert?

**Comment by yjacques940** [comment]
Non ils n'ont pas été transférés dans Cause.Security.Management
