### ISSUE TITLE
CurrentUser should not be attached to context

### ISSUE THREAD

**Issue by CaucaCG** [CAUCA-9-1-1/cause-security-management#41]
**Describe the bug**
Cannot update current user because it is already attached to context

**To Reproduce**
1. Modify the currentUser
2. UpdateUser
3. See error

**Expected behavior**
Save current user must be modify

**Comment by iamkinetic** [comment]
@yjacques940 @CaucaCG  Est-ce qu'on va refaire une nouvelle version qui utilisera le futur Cauca.EntitiesUpdater quand il sera prêt?

Quand vous aurez terminé les ajustements de l'utilisation dans CP, est-ce que vous pourriez mettre à jour la documentation du projet que j'avais écrit pour sa première version?
