### ISSUE TITLE
Add new on properties to make them usable for generic graph update

### ISSUE THREAD

**Issue by yjacques940** [CAUCA-9-1-1/cause-security-management#43]

**Comment by iamkinetic** [comment]
@yjacques940 Est-ce que le pull request pourrait être corrigé svp?  Sinon tes changements seront perdus dans la prochaine version parce qu'ils n'auront pas été merged.

**Comment by yjacques940** [comment]
Si on ne peux pas les new List<> on ne peux pas utiliser l'enregistrement générique.
